### ISSUE TITLE
Mile/Km descriptor selection

### ISSUE THREAD

**Issue by MoBluey** [WJDDesigns/Ultra-Vehicle-Card#1]
Hi, just noticed the values for my vehicle are being pulled correctly however the card does not have the option to toggle between KM's and Miles. Although the value is correct the descriptor shows miles incorrectly. Can we please have a toggle to select between these?

**Comment by WJDDesigns** [comment]
We will be updating and adding soon!

**Comment by WJDDesigns** [comment]
Update made, thanks for the issue reporting!
