### ISSUE TITLE
Capitalize the location entity state if it's not capitalized

### ISSUE THREAD

**Issue by catshapednoodles** [WJDDesigns/Ultra-Vehicle-Card#10]
My car integration provides a device_tracker entity that uses the zones known in Home Assistant as a state. The device_tracker entity uses the exact zone name, so they are properly capitalized (as long as the zone name is capitalized). However, the 'home' and 'away' states are not capitalized. Most/all cards in Home Assistant that use a device_tracker show these as 'Home' and 'Away'. However, this card does not.
Would it be possible to capitalize the device_tracker if the state is not capitalized?

**Comment by WJDDesigns** [comment]
I noticed that too, I'm still learning things but this should be easy to do so you should see this soon! Thanks for the suggestion!

**Comment by WJDDesigns** [comment]
Added in [V1.1.4](https://github.com/WJDDesigns/Ultra-Vehicle-Card/releases/tag/1.1.4) Thanks for the suggestion!
