### ISSUE TITLE
1.6.0: Again wrong Odometer Numbers

### ISSUE THREAD

**Issue by Funkybeatz15** [WJDDesigns/Ultra-Vehicle-Card#100]
Formatted (wrong):
![1](https://github.com/user-attachments/assets/52628083-c3a4-44e6-acfa-33e6e6561eca)

Not formatted (right):
![2](https://github.com/user-attachments/assets/0aa68e48-ab82-46ca-be8f-506333ddfa39)

**Comment by Cornitus** [comment]
Hi there and thanks for your awesome work! 

I have the problem too. The mileage (total) should not be rounded up or down.

Formated: 

![Screenshot_20240914_004720_Chrome](https://github.com/user-attachments/assets/736e9a8d-5028-4d3e-a4f0-163a26d5bd6a)

Not formated:

![Screenshot_20240914_005048_Chrome](https://github.com/user-attachments/assets/726ba3c4-3210-448d-98e4-faed17432287)

The average consumption is also incorrectly formatted. In Germany the point should actually be converted into a coma. But I wouldn't care at all as long as there is a separator at all.

Formated:

![Screenshot_20240914_005327_Chrome](https://github.com/user-attachments/assets/12034bfa-e1b8-4efd-8c66-5a637ca1d0bf)

Not formated:

![Screenshot_20240914_005343_Chrome](https://github.com/user-attachments/assets/d29de520-9ace-453b-be6b-ea7cff0b4c3f)

However, the entities themselves display the values ​​correctly.

![Screenshot_20240914_011315_Chrome](https://github.com/user-attachments/assets/1a22ae28-3f24-40ba-90e3-071381351469)
![Screenshot_20240914_011634_Chrome](https://github.com/user-attachments/assets/628266e2-050f-4446-98bd-f9449cdd5cd9)

It would also be great if 90 minutes were converted into 1h 30m, 120 minutes into 2h and so on.

![Screenshot_20240914_012015_Chrome](https://github.com/user-attachments/assets/cc48bd1b-2464-4da2-a259-571dd0274442)

Thanks for your help and have a nice day!

**Comment by MJHeijster** [comment]
Issue has been fixed in the new beta. 
https://github.com/WJDDesigns/Ultra-Vehicle-Card/issues/75#issuecomment-2351216757

**Comment by Cornitus** [comment]
> Issue has been fixed in the new beta. [#75 (comment)](https://github.com/WJDDesigns/Ultra-Vehicle-Card/issues/75#issuecomment-2351216757)

This is absolutely awesome! Works perfectly! Thank you!
