### ISSUE TITLE
image_entity not working

### ISSUE THREAD

**Issue by M3d1c5** [WJDDesigns/Ultra-Vehicle-Card#105]
Hi guys,

I use the following line in the definition:
`image_entity: sensor.skoda_scala_model_image_url_large`

Information from developer tools:
entity: sensor.skoda_scala_model_image_url_large
state: https://ip-modcwp.azureedge.net/modcwpnw1s22201215/2Y2YJS7NlpzFOAg-uY0vy1cKPZSV_g-zQGfLcD_UYh8IZP-81z_NKcSW6GgYs4AupmEDi-4IdazTsjypM_AHmKPCv68UelhY2tR-OLQFJBI-1080570dayvext_front1080.png
model: Škoda Scala TOUR/2022-02-01
assumed_state: true
icon: mdi:file-image
friendly_name: Skoda Scala Model image URL (Large)

The sensor entity has no entity_picture attribute, but the state contains the picture url.
I think UVC is trying to read the entity_picture attribute. Is that right?

Does it make more sense to ask the developer of the Skoda Connect extension to provide an entity_picture attribute, or can UVC be adapted to read the state if the entity_picture attribute does not exist?

Best regards
Christian

**Comment by WJDDesigns** [comment]
I can look into this further, it should look for any picture not just the entity_picture. We have had to do a lot of reprogramming of code so that might have been messed up when updating. I will take a look!

**Comment by WJDDesigns** [comment]
Fixed in 1.6.3, let me know if you have issues. Restart HA and clear cache!

**Comment by M3d1c5** [comment]
Hey Wayne!

I'm very sorry to say that it's not working yet.
I have installed the update to 1.6.3, restarted Home Assistant and cleared the browser cache.

The following entity is not working:
```
entity: sensor.skoda_scala_model_image_url_large
state: https://ip-modcwp.azureedge.net/modcwpnw1s22201215/2Y2YJS7NlpzFOAg-uY0vy1cKPZSV_g-zQGfLcD_UYh8IZP-81z_NKcSW6GgYs4AupmEDi-4IdazTsjypM_AHmKPCv68UelhY2tR-OLQFJBI-1080570dayvext_front1080.png
model: Škoda Scala TOUR/2022-02-01
assumed_state: true
icon: mdi:file-image
friendly_name: Skoda Scala Model image URL (Large)
```

The following entity works:
```
entity: device_tracker.skoda_scala_position
state: home
source_type: gps
latitude: XXXXXXX
longitude: XXXXXXX
gps_accuracy: 0
model: Škoda Scala TOUR/2022-02-01
entity_picture: https://ip-modcwp.azureedge.net/modcwpnw1s22201215/2Y2YJS7NlpzFOAg-uY0vy1cKPZSV_g-zQGfLcD_UYh8IZP-81z_NKcSW6GgYs4AupmEDi-4IdazTsjypM_AHmKPCv68UelhY2tR-OLQFJBI-700390dayvext_front1080.png
assumed_state: true
icon: mdi:car
friendly_name: Skoda Scala Position
```

Apparently, only the “entity_picture” attribute is still being read.
I have also noticed that the entity filter “Search entity” does not filter correctly.

Have a nice day!
Christian

**Comment by WJDDesigns** [comment]
Christian, can you hop in our discord so we can help you? https://discord.gg/6xVgHxzzBV

**Comment by MartinAirN** [comment]
> The following entity is not working:
> 
> ```
> entity: sensor.skoda_scala_model_image_url_large
> state: https://ip-modcwp.azureedge.net/modcwpnw1s22201215/2Y2YJS7NlpzFOAg-uY0vy1cKPZSV_g-zQGfLcD_UYh8IZP-81z_NKcSW6GgYs4AupmEDi-4IdazTsjypM_AHmKPCv68UelhY2tR-OLQFJBI-1080570dayvext_front1080.png
> model: Škoda Scala TOUR/2022-02-01
> assumed_state: true
> icon: mdi:file-image
> friendly_name: Skoda Scala Model image URL (Large)
> ```

Is this an entity you created yourself? or one that is provided to you?

As there is an "image" helper. It can be found at "Add Helper" -> "Template" -> "Image"

**Comment by geekypenguin** [comment]
Did you manage to find a solution to this?
I'm trying to use a template sensor to show multiple charging states by changing the main image with an entity.

I have a template sensor that returns an image url for each state I'm displaying, but it's not being shown by the card

**Comment by WJDDesigns** [comment]
Closing this issue due to no communication or we are helping on Discord. This is indeed working on our end.
