### ISSUE TITLE
Feature Request: Dynamic Icons

### ISSUE THREAD

**Issue by mtwilliams5** [WJDDesigns/Ultra-Vehicle-Card#106]
First off, just installed this component, and am loving playing around with it. Great work!

These might be features that exist that I haven't figured out yet, or one that may be possible but undocumented, but there are a couple of things that I'd like to be able to do with the icons in the grid to make it easier to create a clean interface:

* Dynamically remove (not render) icons in the grid based on state. There's the 'no icon' toggle that can be used by state, but the space the icon would take up is still there, so you can end up with gaps in the grid. As a bonus, it'd be great to be able to hide/show icons based on _another_ entity's state, but I get that that would add more complication into the UI configurator.
* Allow trigger/toggle/call-service using an entity other than the one used for the icon. One example use case for this: I have a separate lock sensor and lock entity. The lock sensor has attributes that let me tell the state of each individual door, which could be useful to display, but the interaction I'd want for any of those would be to trigger the lock entity, or call the lock.lock or lock.unlock service, passing the lock entity as the entity ID. A quick look through the code shows that I can set call-service as the interaction, but it hard-codes the entity ID to the one used for the icon, and you can't seem to pass any additional metadata

**Comment by WJDDesigns** [comment]
> First off, just installed this component, and am loving playing around with it. Great work!

Awe stop, you're buttering me up!

> Dynamically remove (not render) icons in the grid based on state. There's the 'no icon' toggle that can be used by state, but the space the icon would take up is still there, so you can end up with gaps in the grid. As a bonus, it'd be great to be able to hide/show icons based on another entity's state, but I get that that would add more complication into the UI configurator.

Not sure about showing/hiding based on state as we are trying to keep this clean for even beginners to figure out, but who knows you might just see it later down the road. The icon should not take up space if it is set to no icon so I will be looking at that.

> Allow trigger/toggle/call-service using an entity other than the one used for the icon. One example use case for this: I have a separate lock sensor and lock entity. The lock sensor has attributes that let me tell the state of each individual door, which could be useful to display, but the interaction I'd want for any of those would be to trigger the lock entity, or call the lock.lock or lock.unlock service, passing the lock entity as the entity ID. A quick look through the code shows that I can set call-service as the interaction, but it hard-codes the entity ID to the one used for the icon, and you can't seem to pass any additional metadata

Fair requests and possibly will be part of the template system we are working on which is still in beta.

**Comment by WJDDesigns** [comment]
Closing this but may look at it in the future version.
