### ISSUE TITLE
Shows lots of decimals

### ISSUE THREAD

**Issue by nikee73** [WJDDesigns/Ultra-Vehicle-Card#111]
On the card:
Odometer shows 340.75420672 km
And range shows 240.20901172224 km
Both entities are set to use zero decimals
If I click range or odo then it shows only with zero decimals

HA and Ultra Vehicle Card is updates to latest version

**Comment by WJDDesigns** [comment]
Is the format entities toggle on in the settings tab?

**Comment by Hubszo** [comment]
Same issue. Format entities is toggeled on but no effect.

**Comment by WJDDesigns** [comment]
Have you both tried the beta?
