### ISSUE TITLE
Icon Interaction Call Service missing from dropdown

### ISSUE THREAD

**Issue by c4weddell** [WJDDesigns/Ultra-Vehicle-Card#117]
I am looking to call a service from an icon in the icon grid but when I select the dropdown the 'Call Service' option mentioned in the readme is missing...
![image](https://github.com/user-attachments/assets/2ab3c9e4-222e-458c-857e-dbe042d3002c)

**Comment by WJDDesigns** [comment]
Can you use Trigger and see if that works?

**Comment by c4weddell** [comment]
I think that works if I have understood it correctly...

I have created a new automation that calls the update service that I was wanting to call directly.  I then use that automation as the entity and I select Trigger to trigger the automation?

**Comment by WJDDesigns** [comment]
> I think that works if I have understood it correctly...
> 
> I have created a new automation that calls the update service that I was wanting to call directly. I then use that automation as the entity and I select Trigger to trigger the automation?

That is certainly one way of doing it. We might add the call service feature but then to do it right we will add a field so you can put in the service to call. Triggers are meant to one time make something happen versus toggle is on/off.
