### ISSUE TITLE
State language 

### ISSUE THREAD

**Issue by Amokk123** [WJDDesigns/Ultra-Vehicle-Card#119]
The state language is still not translated. 
Cache cleared. All the other value ar translated (Norwegian). Tried uninstall, and reboot. Install again, but still same issue. 
![Screenshot_2024-09-28-18-42-07-04_4641ebc0df1485bf6b47ebd018b5ee76](https://github.com/user-attachments/assets/ba5cf70d-bad9-4e4d-bf56-585cd1f689ca)

**Comment by WJDDesigns** [comment]
You should try the newest version. This has been working I believe for awhile but always try the newest version.

<img width="484" alt="Screenshot 2024-10-04 at 7 28 53 AM" src="https://github.com/user-attachments/assets/87daa32b-f185-46b8-a9a7-b73d6048e27e">

We have translated files for NB and NN.
