### ISSUE TITLE
Extra padding in "Double Column"layout type

### ISSUE THREAD

**Issue by mattdevo1** [WJDDesigns/Ultra-Vehicle-Card#121]
When switching from single column to double column it looks like an additional 16px of padding is added around the card. See screenshots below. 

Not the biggest deal in the world, but a bit of a waste of space and IMO doesn't look the best. 

I changed this with card mod, but might be worth changing by default. 

![image](https://github.com/user-attachments/assets/98434f36-5e6c-4ad4-bd81-f78912e8ef48)

![image](https://github.com/user-attachments/assets/f88e7b9c-fba6-47e9-aadd-2c2b359a2af5)

**Comment by WJDDesigns** [comment]
This has been fixed in newest update, thanks for letting me know!

**Comment by mattdevo1** [comment]
Looks like that did the trick, thanks!!
