### ISSUE TITLE
Icon label is not shown

### ISSUE THREAD

**Issue by Speederer** [WJDDesigns/Ultra-Vehicle-Card#125]
Hi,
I would like to see the values below the icons, but this feature doesn't work for me. Actually I'm new in this card (installed today), but I think the "Icon Label Position" is for this purpose. So I changed from None to e.g. Bottom, but nothing happened.
![2024-10-07 12_15_42-Home Assistant - Autó – Home Assistant](https://github.com/user-attachments/assets/ca85f10b-2960-4ad7-9e63-ad469d4dce9f)
![2024-10-07 12_15_55-Home Assistant - Autó – Home Assistant](https://github.com/user-attachments/assets/9376b049-ca52-450e-a3e8-9c2d735f988a)

Did I do something wrong? Or is this a bug?
I'm using the latest version (v.1.6.7).

**Comment by matttheotter** [comment]
Ah well this makes me feel better that its not just me.

Can you check your HA logs and see if its throwing up any errors related to Ultra? I got the following.

Are you using Firefox? Safari? Chrome? HASS on a local server?

`Logger: frontend.js.modern.202410022
Source: components/systemlog/_init.py:331
First occurred: 19:57:57 (312 occurrences)
Last logged: 21:47:43

Uncaught error from Firefox 131.0 on Mac OS 10.15 TypeError: "icon_gap" is read-only _updateRowSeparatorConfig (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:1396:7) _renderRowSeparatorDetails/< (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2680:24) handleEvent (/lit-html@1.4.1/lib/parts.js:462:18) EventPart/this.boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
Uncaught error from Firefox 131.0 on Mac OS 10.15 TypeError: "sensor.plug_state" is read-only _updateIconLabel (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2585:5) _renderEntityDetails/< (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:1317:24) handleEvent (/lit-html@1.4.1/lib/parts.js:462:18) EventPart/this.boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
Uncaught error from Firefox 131.0 on Mac OS 10.15 TypeError: "sensor.charge_state" is read-only _updateIconLabel (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2585:5) _renderEntityDetails/< (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:1317:24) handleEvent (/lit-html@1.4.1/lib/parts.js:462:18) EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41) (edited)
[21:49]
Uncaught error from Firefox 131.0 on Mac OS 10.15 TypeError: can't define property "sensor.plug_state": Object is not extensible _updateIconLabel (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2585:5) _renderEntityDetails/< (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:1317:24) handleEvent (/lit-html@1.4.1/lib/parts.js:462:18) EventPart/this.boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
Uncaught error from Firefox 131.0 on Mac OS 10.15 TypeError: can't define property "binary_sensor.charging": Object is not extensible _updateIconLabel (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2585:5) _renderEntityDetails/< (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:1317:24) handleEvent (/lit-html@1.4.1/lib/parts.js:462:18) EventPart/this.boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)`

**Comment by Speederer** [comment]
I get an error if I choose a non-default value (e.g. Bottom) for Icon label position, but a different one than you.

Uncaught error from Chrome WebView 129.0.6668.70 on Android 14 TypeError: Cannot add property sensor.ioniq_5_last_updated_at, object is not extensible UltraVehicleCardEditor._updateIconLabel (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2585:39) UltraVehicleCardEditor.<anonymous> (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:1317:24) EventPart.handleEvent (/lit-html@1.4.1/lib/parts.js:462:18) EventPart.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)

It is enough to make change without saving the dashboard changes.
Last time I tried it from Android HA application, but earlier from my PC with a Chrome browser. The result is the same.

**Comment by matttheotter** [comment]
@Speederer - are you running anything on your home network like Adguard?

**Comment by WJDDesigns** [comment]
Fixed in V1.6.8-beta3!
