### ISSUE TITLE
What Data Type is Needed for Fuel Level and Fuel Range?

### ISSUE THREAD

**Issue by jianyu-li** [WJDDesigns/Ultra-Vehicle-Card#126]
Whenever I set entities for these two the card always disappears

**Comment by WJDDesigns** [comment]
I am not sure why it is doing this for you? For fuel level you need an entity that is using percentage based 0-100%. For range just any milage entity will work.

**Comment by jianyu-li** [comment]
I did some more testing, the integration does return a percentage fuel level and it blanks out my card. I tested with a template sensor in decimal format (no percentages) and it worked. So as a workaround I'll just create a template sensor and use that.

**Comment by jianyu-li** [comment]
Just another observation I wonder if my integration is actually returning a string. My template sensor returns a decimal with a unit_of_measurement of "%". Anyway, I got it working.
