### ISSUE TITLE
Car doesn't have a fuel level in % only in Liters.

### ISSUE THREAD

**Issue by mrsofa** [WJDDesigns/Ultra-Vehicle-Card#127]
Hey I would like to add my range in liters because my car doesn't output the percentage.

Is it possible to achieve this? So the logic would be to input the tank size and then I have the entity fuel remaining in liters.

Thanks

**Comment by mrsofa** [comment]
Okay sorry for opening this up and solving it right away but i will leave the code if anyone finds this useful:

Create a new template sensor that converts the liters to percentage.
Add this to your configuration.yaml or use the Template Editor in Home Assistant to create a new sensor:

`sensor:
  - platform: template
    sensors:
      bmw_320i_fuel_percentage:
        friendly_name: "BMW 320i Fuel Percentage"
        unit_of_measurement: "%"
        value_template: >
          {% set liters = states('sensor.320i_remaining_fuel') | float %}
          {{ (liters / 65 * 100) | round(0) }}`
          
This template takes the current fuel level in liters from the sensor.320i_remaining_fuel entity and divides it by 65 (the maximum fuel capacity in liters), then multiplies by 100 to convert it into a percentage. Change 65 to your tank size.

Update the Ultra Vehicle card YAML to use the new percentage sensor:

`fuel_level_entity: sensor.bmw_320i_fuel_percentage`

**Comment by WJDDesigns** [comment]
This is exactly how it is done. I will go ahead and add your example to the docs, thanks!
