### ISSUE TITLE
Adaptation to Light/Dark mode

### ISSUE THREAD

**Issue by kimme1024** [WJDDesigns/Ultra-Vehicle-Card#131]
Hi,

First of all thanks for this! It really looks great!
The only thing I currently seem to miss is the possibility for the colours to switch when going from light to dark mode.

I have a wall tablet that's constantly on dark mode and on the phones it automatically switches during the day.
However the card remains the chosen color.

Would it be possible to have the colors adapt to these modes?

If it's already possible, sorry I missed it but could someone put me in the right direction to fix it?

Thanks!

**Comment by WJDDesigns** [comment]
We support all themes but each time you would need to hit the reset icon for it to pull in the current colors, that is why we made a global reset. The reason why we do this is we convert the css var(--primary-color) for example to a hex code to make it easier for users to copy and paste the hex code in so it converts that. This makes it so it is not automatic so we have to juggle between ease of use and auto. We might adjust this moving in the future but for right now this how it works.

**Comment by kimme1024** [comment]
Hi,

I already tried hitting the reset button as described in another topic. However the card still shows completely whtie and doesn't change at all. The only option is to manually change all the colors on each change.
Let's hope this will be changed in the future as it's kind of a hassle if I have to manually each time...
