### ISSUE TITLE
Fuel capacity displayed in percentage instead of liters

### ISSUE THREAD

**Issue by mountainbikert** [WJDDesigns/Ultra-Vehicle-Card#134]
My fuel capacity entity of my displays the remaining fuel in liters. In the ultra card it shows in percentage. Is there a way to implement this so it show the right amount?

**Comment by WJDDesigns** [comment]
@mattdevo1 is correct, you need to use a template sensor to convert that. Follow our wiki to do that here: https://github.com/WJDDesigns/Ultra-Vehicle-Card/wiki/Template-Sensor-for-Fuel-Percentage
