### ISSUE TITLE
Perform-action UI support

### ISSUE THREAD

**Issue by neo42JBR** [WJDDesigns/Ultra-Vehicle-Card#137]
Adding to #70 I see some gripes with the implementation atm. I have the exact use case that @Sleeepy2 has.

- No UI support: Changing anything via UI config will delete the YAML entry.
- No confirmation support. Adding a confirmation to the config will not trigger a popup

**Comment by WJDDesigns** [comment]
Have you tried newest beta?

**Comment by WJDDesigns** [comment]
Try the newest build out, it should be fixed.

**Comment by neo42JBR** [comment]
@WJDDesigns: I am sorry, I was on a business trip. I updated to the newly release 1.6.8 but cannot tell that anything changed?

**Comment by WJDDesigns** [comment]
Join our Discord to see if anyone there can help as it seems this is not a normal issue we are seeing from multiple people. https://discord.com/invite/kpZVgAVF
