### ISSUE TITLE
icon Grid States

### ISSUE THREAD

**Issue by seang96** [WJDDesigns/Ultra-Vehicle-Card#138]
The active / inactive icons are always going to inactive for me. I even tried templating to return true when state of my lock is "locked" and it still fails to register. I am running Home Assistant 2024.10.3.

Besides the buttons not working everything else seems to be working well. Thanks for the good looking card!

**Comment by WJDDesigns** [comment]
Which version are you running?

**Comment by seang96** [comment]
For the card, it's the latest on 1.6.7.

**Comment by WJDDesigns** [comment]
Try the newest Beta and let me know if it fixes it.

**Comment by seang96** [comment]
Default for lock fails but the template works at least!
