### ISSUE TITLE
Labels for icons not displayed

### ISSUE THREAD

**Issue by jahoooo** [WJDDesigns/Ultra-Vehicle-Card#140]
Using v1.6.7, whenever I select a label of any icon to be displayed (e.g. bottom) the label is not displayed.
When I check again the config setting over the UI, it got set back to icon label position "none".
Somehow all the label position settings are not being stored / accepted.

**Comment by WJDDesigns** [comment]
Have you tried the newest Beta?

**Comment by jahoooo** [comment]
Was not sure how stable the beta's are. But now I'm using 1.6.8-beta7, which looks stable so far and the issue is solved!
