### ISSUE TITLE
Feature Request: Color Icons By Value Threshold

### ISSUE THREAD

**Issue by jlmaners** [WJDDesigns/Ultra-Vehicle-Card#145]
As it is starting to get colder here in North America, I wanted to add Tire Pressure read outs to the card and had planned to use icon grid as a way to show each tire and its pressure. While we can color an icon if the sensor has a state of off/on, I was wondering if it would be possible to see number thresholds so we could color if a numeric sensor is below a certain value. That way it'd change colors if tire pressure was below what it should be?

I'm already working to get push notifications if the tire pressure reading drops below a certain threshold but thought it'd be nice to see something on the card as well.

**Comment by WJDDesigns** [comment]
{{ [60, [10, states('sensor.your_sensor') | float] | max] | min }}

Replace sensor.your_sensor with the entity you want to restrict. Here’s how it works:
	1.	states('sensor.your_sensor') | float retrieves the sensor’s value and converts it to a float.
	2.	[10, sensor_value] | max ensures the value is at least 10.
	3.	[60, result] | min caps the value at 60.
	
	Try that above using the template function for each icon and that should work, let me know!

**Comment by jlmaners** [comment]
I totally missed the template mode 🤦‍♂️

Ended up just using the following:
 `{{ states('sensor.front_driver_tire_rav4') | float < 28 }}`
 And that changes the color to Orange as an alert. 
 
 Thanks for the help!

**Comment by WJDDesigns** [comment]
No problem, glad you got it working!
