### ISSUE TITLE
Custom element doesn't exist: ultra-vehicle-card

### ISSUE THREAD

**Issue by Soodium** [WJDDesigns/Ultra-Vehicle-Card#147]
Hello, I have the following setup:

1 Fire Tablet (client, no internet access)
1 Home Assistant (host, internet access)

As soon as I disable internet access for the Fire Tablet and want to use it locally only, Home Assistant shows the error: "ultra-vehicle-card doesn’t exist." Why does the ultra-vehicle-card require an internet connection? Is it possible to use it entirely locally? When I re-enable internet access, everything works fine on the tablet. If internet access is absolutely necessary for this card, which IP address should I whitelist?

Nothing to see in the logs :-(

Thank you in advance!

![390175382-831eaa19-df5d-4674-ab60-c094f7044074](https://github.com/user-attachments/assets/3abac8a0-a755-4cbb-9f37-ed3de62ed884)

**Comment by WJDDesigns** [comment]
The code uses external modules for styling and resources. It needs internet connection to reach those resources.

**Comment by Soodium** [comment]
Can i find the destinations anywhere so that i can whitelist them?

**Comment by WJDDesigns** [comment]
> Can i find the destinations anywhere so that i can whitelist them? 

I would whitelist anything from https://unpkg.com as it is used for many integrations.

**Comment by Soodium** [comment]
Thank you very much for the quick response. It worked!

**Comment by sshaikh** [comment]
> > Can i find the destinations anywhere so that i can whitelist them?
> 
> I would whitelist anything from https://unpkg.com as it is used for many integrations.

This is super useful and should be put in the readme or a FAQ - or even better have the card surface this error (if possible).
