### ISSUE TITLE
Feature suggestion: controllable icons

### ISSUE THREAD

**Issue by akamming** [WJDDesigns/Ultra-Vehicle-Card#153]
Hi,

i just started using Home Assistant and found this great addon for the dashboard. First of all. Thank you very much. This work is very much appreciated, it looks great!

I have a suggestion to make it even better though:

The card now just shows information from the car. But it would be great if i could also use it to give some commands:

My car supports many commands by the API:
- honk / flash
- lock/unlock
- start / stop climatization

I already added icons for the lock and climatization. But if possible i would love that i could click those items and then it would send on/off or lock/unlock commands...

**Comment by MightyMeik** [comment]
+1 for this request.
I like to create an icon to authorize the EV-Loader (start loading), but for my EV-Loader (easee) it is only pissible via HA action command

**Comment by K3str3l** [comment]
There is an option to have actions performed for each icon
![image](https://github.com/user-attachments/assets/0fe0e271-54e3-49f9-a4a6-cfaea6093772)

**Comment by K3str3l** [comment]
What is available may differ from model to model....

**Comment by akamming** [comment]
That indeed works, closing this issue
