### ISSUE TITLE
Light mode charge bar has low contrast

### ISSUE THREAD

**Issue by domoritz** [WJDDesigns/Ultra-Vehicle-Card#16]
It looks like the light mode charge bar has not been optimized. The blue has low contrast to the black background. 

![image](https://github.com/user-attachments/assets/9f0621f0-42a0-47b5-bd85-80fa56b2093a)

![image](https://github.com/user-attachments/assets/91914449-a2c1-4d35-9349-5fc93cc4a400)

**Comment by WJDDesigns** [comment]
I personally think the bar BG works well in both cases especially since people will be using their primary color. If I have more need from this I'll implement a light/dark variant for bar BG.

**Comment by domoritz** [comment]
Thanks for chiming in. I think making sure that the bar satisfies [minimum contrast ratios for WCAG](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) would be good.

**Comment by WJDDesigns** [comment]
Man you're throwing WCAG at a web dev ugh so now back against the wall lol I know some people like things dark. I'll end up selecting something that works or soon I might allow custom colors :)

**Comment by AlexandreLogist** [comment]
I think it is even worse with my theme (Material Rounded No Mod Light)
![image](https://github.com/user-attachments/assets/55275149-26b6-4a17-b11f-75a116288521)

**Comment by AlexandreLogist** [comment]
+ app
![Screenshot_20240806_102555_Home Assistant.jpg](https://github.com/user-attachments/assets/3f86c441-7bf3-4ede-b0fe-d036171871a5)

**Comment by WJDDesigns** [comment]
Yeah I'm switching the default to a compliant contrast AND adding in a custom colors area so people can also make their own theme.

**Comment by WJDDesigns** [comment]
<img width="921" alt="Screenshot 2024-08-06 at 9 04 20 AM" src="https://github.com/user-attachments/assets/2ea93b17-098c-4a02-81e6-18df2555ff7a">
<img width="918" alt="Screenshot 2024-08-06 at 9 05 18 AM" src="https://github.com/user-attachments/assets/60beab9f-03fb-48e1-8518-190b30804fbd">


New color follows WCAG for the default and will change depending on dark/light.

**Comment by WJDDesigns** [comment]
Fixed in latest build!

**Comment by AlexandreLogist** [comment]
Looking great, thank you !

**Comment by WJDDesigns** [comment]
<img width="481" alt="Screenshot 2024-08-06 at 4 15 26 PM" src="https://github.com/user-attachments/assets/6113d2fa-2047-41f5-8640-30f92d89db0c">

Time to get colorful!
