### ISSUE TITLE
Charging is no longer indicated

### ISSUE THREAD

**Issue by sanchosk** [WJDDesigns/Ultra-Vehicle-Card#23]
I have a problem with this line of code:
`  const isCharging = chargingStatusEntity && chargingStatusEntity.state.toLowerCase() === 'charging';`
On my car, the charging entity is a boolean item and it has on/off status based on the current state of the vehicle.
I don't have any status that would be showing "charging".
I can do a workaround and provide virtual status, of course, but it would be nicer if the extension could detect the type of the sensor and if it is boolean, act accordingly, if it is sensor, compare it with some word...

**Comment by cgilis** [comment]
+1

**Comment by WJDDesigns** [comment]
> Hey @WJDDesigns 1.1.9 does not fix this issue.

I know fixing the fix, wait a second.

**Comment by WJDDesigns** [comment]
> Hey @WJDDesigns 1.1.9 does not fix this issue.

Can you try V1.1.10

**Comment by cgilis** [comment]
Just tried it, @WJDDesigns .. no difference, strange..

**Comment by WJDDesigns** [comment]
Now is this for the info are for car state or is this for the charging entity to show the animation and the word charging next to percent?

**Comment by cgilis** [comment]
This is for charging entity

![CleanShot 2024-08-08 at 17 23 43@2x](https://github.com/user-attachments/assets/dbf30e8d-32b9-4f7a-8093-85428abed3a0)

**Comment by cgilis** [comment]
It's like @sanchosk is saying it's easily fixable with a helper, but would be nice if it would work out of the box :-)

**Comment by WJDDesigns** [comment]
https://discord.gg/xKGN3SVg can anyone join my Discord so we can chat to see if I can fix this issue?
