### ISSUE TITLE
Feature request: Add localization 

### ISSUE THREAD

**Issue by PottiMc** [WJDDesigns/Ultra-Vehicle-Card#25]
Hey, I really love your card. Thanks for your work!
It would be awesome to get some localization to other languages (mainly the "90% Fuel" text in the card and the name of the home zone)

If you need some help with translation to German I am willing to help.

**Comment by magune** [comment]
PottiMc I also want the %Fuel label to be translated (into Swedish).

**Comment by Mamouti** [comment]
Hello, I can do French translation.

**Comment by patrick11994** [comment]
I can do the dutch translation

**Comment by WJDDesigns** [comment]
I might be able to do auto translation :)

**Comment by WJDDesigns** [comment]
Localization should be working on v1.5.0 😀

**Comment by PottiMc** [comment]
Thank you very much!
