### ISSUE TITLE
Feature request: Image from entity

### ISSUE THREAD

**Issue by haraldpaulsen** [WJDDesigns/Ultra-Vehicle-Card#28]
The integration I'm using (Skoda) has the URL of the car image stored in an entity.

Can you add the option of using an entity as the image source?

entity id: sensor.oda_model_image_url_large
name: Oda Model image URL (Large)
content: https://ip-modcwp.azureedge.net/blablablatruncated/front.png

**Comment by nsimons** [comment]
Also looking for this feature!
Volvo has the image stored in an `image.` sensor (i.e. entity ID: `image.volvo_<vin>_exterior_image`).

**Comment by MartinAirN** [comment]
Support for templates would also fix this issue (and allow for conditional values, such as open/closed doors)

**Comment by WJDDesigns** [comment]
I can allow the main image field to accept entities as well as templates if that would fix things.

**Comment by WJDDesigns** [comment]
Image from entity added!
