### ISSUE TITLE
Feature request: Custom color for icons

### ISSUE THREAD

**Issue by patrick11994** [WJDDesigns/Ultra-Vehicle-Card#30]
I would like to set up different colors for the icons and their state so I can make them look like the icons on the dash.

Example for when all warning lights are active:
![afbeelding](https://github.com/user-attachments/assets/66f88139-3cb6-42d3-b0b9-6c499d43aa33)

**Comment by WJDDesigns** [comment]
I like this idea maybe I should move those colors from the bottom to each icon, good idea.

**Comment by WJDDesigns** [comment]
Custom colors for each icon added in V1.3.1
