### ISSUE TITLE
Feat: Door Open Display

### ISSUE THREAD

**Issue by jacauc** [WJDDesigns/Ultra-Vehicle-Card#31]
How about a feature where the vehicle image is changed to another top-down view of the car when any door is open. Or having an overlay that is applied when doors are open. When all doors are closed, it returns to the normal vehicle image.

The Mercedes App screenshot below is an example of what I mean
![image](https://github.com/user-attachments/assets/709c35ef-ff0c-4d3c-82a0-175fd3f87c41)

**Comment by WJDDesigns** [comment]
I heard if I put in the ability to do templates you will be able to make that happen as well.

**Comment by WJDDesigns** [comment]
You might be able to make this now using entities to select... I believe in theory you can select a template you made from within HA.

**Comment by jacauc** [comment]
I'm still not really clear on how this could be achieved? Could you perhaps give me a nudge in the right direction?

**Comment by WJDDesigns** [comment]
You can use Home Assistant’s templating feature to dynamically change the image based on the state of another entity, such as a door sensor. Here’s a template example that updates an image entity based on whether a vehicle door is open or closed: 

type: picture-entity
entity: sensor.door_status
state_image:
  "open": /local/images/door_open.png
  "closed": /local/images/door_closed.png
image: >-
  {% if is_state('binary_sensor.vehicle_door', 'on') %}
    /local/images/door_open.png
  {% else %}
    /local/images/door_closed.png
  {% endif %}

1. sensor.door_status: This would be the entity representing the door status (you can adjust this to match your entity).
2. state_image: This sets specific images for the states (open and closed).
3. image: The template dynamically selects the image based on the door sensor state (on for open, off for closed).

Make sure the images are stored in the /config/www/images/ folder, and replace binary_sensor.vehicle_door with the actual entity ID of your door sensor.

Then in the card you should be able to pull in the sensor.door_status and in theory it would pull the correct image based on what the status is. I would keep in mind that the car integrations you use in HA are not instant so if someone opens a door it might take a few minutes or seconds to update depending on when that integration polls.
