### ISSUE TITLE
Feature Request: Metric Units choice

### ISSUE THREAD

**Issue by muster021** [WJDDesigns/Ultra-Vehicle-Card#32]
Ability to change between km or metric miles. 
I can change between imperial units (mi) and metric (km), but my integration (Volvo) reports range etc in metric miles, for example 10 miles = 100 km. So the card says 10 km range, while it is in fact 100 km.

**Comment by sohlman67** [comment]
Another option would be to actually pull the relevant unit from the enitys' attribute: unit_of_measurement, if it exists.
It will most likely be there for an odometer entity in any car-integration. 
I.e. in Sweden we have both 'km' and 'mil' which is not the same as the english 'mile'.

**Comment by WJDDesigns** [comment]
This is a great idea, I'll add it in for next update!

**Comment by WJDDesigns** [comment]
Fixed in 1.3.1 :)
