### ISSUE TITLE
Custom location showing 'friendly name' from device_tracker not the actual custom zone entity

### ISSUE THREAD

**Issue by lundan** [WJDDesigns/Ultra-Vehicle-Card#34]
https://github.com/WJDDesigns/Ultra-Vehicle-Card/blob/4e2ca44d78c70159a61a3a50393d44112a0406b6/ultra-vehicle-card.js#L402

**Comment by JHarding86** [comment]
I have this same issue. Instead of my location showing, it is displaying the friendly name of the entitiy:

![image](https://github.com/user-attachments/assets/55af1c36-e06e-4640-8fbb-7cda950a1546)

**Comment by WJDDesigns** [comment]
I might be adding in actual street address from GPS as well.

**Comment by mattdevo1** [comment]
I'm having the same issue:

![image](https://github.com/user-attachments/assets/e8fce481-2202-4bdf-bc88-a87dbeaea4c2)

**Comment by Jeppedy** [comment]
Ditto

**Comment by WJDDesigns** [comment]
This has been fixed but waiting to push the update since I am fixing a few things.

**Comment by WJDDesigns** [comment]
Can you check if this has been fixed?

**Comment by JHarding86** [comment]
> Can you check if this has been fixed?

My card is showing the same as before. It doesn't appear to be fixed. 

![image](https://github.com/user-attachments/assets/04e79119-ed5a-47ee-88e1-d311b4c530b2)

**Comment by WJDDesigns** [comment]
Can you join my Discord channel for this card so we can see what the issue might be? https://discord.gg/WBQCuDBm

**Comment by lundan** [comment]
Working correctly for me, thanks! 😃
