### ISSUE TITLE
The card should support the HA provided themes

### ISSUE THREAD

**Issue by raducotescu** [WJDDesigns/Ultra-Vehicle-Card#36]
Currently the card provides its own basic styling options in the form of colour pickers for various elements. However, if one uses HA themes which also react to the device’s dark mode, the styling provided by the card doesn’t automatically adapt.
![IMG_5909](https://github.com/user-attachments/assets/6567627c-f9bc-4957-8d48-98b462ea2e47)
![IMG_5908](https://github.com/user-attachments/assets/04c3b335-2ceb-4f13-a764-b9d8299b29c0)

**Comment by WJDDesigns** [comment]
Currently we added default colors for light and dark mode. If you are on dark or light just click the reset button next to the color and it will default to the correct colors for the regular theme Dark Or Light in V1.3.1 .

**Comment by raducotescu** [comment]
I think there was a misunderstanding. The icon should react to light/dark mode changes. It's the only card I have on my instance that doesn't, since instead of using the HA conventions you hardcode colour values.

**Comment by raducotescu** [comment]
And it does work as it should, though there were some hiccups where the editor script was still saving `#ffffff` as the background colour for the card. I've managed to overcome that by switching to code view and sending a payload without any colour definitions. Thank you!

**Comment by WJDDesigns** [comment]
Yeah at this time I've updated it so much that it might need a new card added or using code editor to fix some quirks. I'm glad you were able to see the fix though!
