### ISSUE TITLE
Remaining range not showing

### ISSUE THREAD

**Issue by jackyoung1** [WJDDesigns/Ultra-Vehicle-Card#38]
I have added a sensor with remaining range to the card config, but it doesnt show in the card

I dont have an entity with % charge, so have left this blank

**Comment by MrBlue90** [comment]
+1
I experience the same issue since one of the recent updates.

**Comment by WJDDesigns** [comment]
This entity should be a sensor with the state 1-100 is it not?

**Comment by jackyoung1** [comment]
No, remaining range is distance

**Comment by MartinAirN** [comment]
Could you share your config and screenshot of how it looks? Perhaps with an example of what you expect.

**Comment by MrBlue90** [comment]
![image](https://github.com/user-attachments/assets/82e5d886-a5e2-487d-93b6-cad499965bf8)

`type: custom:ultra-vehicle-card
title: Hyundai Tucson
image_url: >-
  https://vehicle-images.dealerinspire.com/stock-images/chrome/400e243081e3655168b59466fa1fbcc6.png
vehicle_type: Fuel
unit_type: km
level_entity: sensor.tucson_fuel_level
range_entity: sensor.tucson_fuel_driving_range
location_entity: device_tracker.tucson_location
mileage_entity: sensor.tucson_odometer
show_level: true
show_range: true
show_location: true
show_mileage: true
icon_grid_entities:
  - lock.tucson_door_lock
  - binary_sensor.tucson_fuel_low_level
  - binary_sensor.tucson_washer_fluid_warning
  - binary_sensor.tucson_tire_pressure_all
  - binary_sensor.tucson_trunk
custom_icons:
  binary_sensor.tucson_trunk: mdi:bag-checked
  lock.tucson_door_lock: mdi:car-door-lock-open
  binary_sensor.tucson_fuel_low_level: mdi:gas-station
  binary_sensor.tucson_washer_fluid_warning: mdi:wiper-wash-alert
  binary_sensor.tucson_tire_pressure_all: mdi:car-tire-alert
`

![image](https://github.com/user-attachments/assets/da511ae5-8ca3-4347-ae96-df4337045cb8)

**Comment by MartinAirN** [comment]
Ah, you are experiencing a mismatch in the frontend and backend. Most likely due to a caching issue.

If you open login and edit the tile in a private browser my guess it that it will work.
If it does, clearing your cache in the app and/or browser will fix the issue.

**Comment by WJDDesigns** [comment]
Please download the newest update as well as restart HA and clear frontend cache, thanks!

**Comment by MrBlue90** [comment]
Thanks gentlemen!
Updating to 1.3.1, rebooting HA, using incognito browsing (to avoid cache) and reapplying the new settings in the card solved the issue!
