### ISSUE TITLE
"Active" vs "Inactive" isn't intuitively consistent with entity state.

### ISSUE THREAD

**Issue by jayscovill** [WJDDesigns/Ultra-Vehicle-Card#39]
I hope I can explain this in a way that makes sense.

Currently the configuration of the icon grid entities use the terms "active" and "inactive" to determine the icon and colour used.  But there are cases where those terms don't intuitively represent the state of the entity.

For instance, the lock entity for my vehicle is either "locked" or "unlocked".  However the card considers the "locked" state to be "Inactive".  This results in the icon colour being red (My "Inactive Colour" is set to Red and "Active" to green) when intuitively it should be the opposite.  Red for "unlocked" and green for "locked".

This also applies to the icon.  "Inactive" intuitively would mean "Unlocked" which causes a problem trying to display the correct icon based on the entity state and doesn't match up with other entities such as the engine which uses "Active" for on and "Inactive for off (and is logical).

Another example is the plugged-in state.  Intuitively "Active" would be "plugged in" (green) and "Inactive" would be "unplugged" (red).  But the card treats those in reverse so you end up with the icon being red when it's "plugged in" and "green" if "unplugged" if enabling "Use Active Color".

A couple of proposed solutions would be to a) allow you to specify active/inactive colour and icons for each individual grid entity or b) allow you to set icon and colour based on the actual state of each grid entity rather than how they are treated as "active" or "inactive".

Thanks for hearing me out and please let me know if I'm totally out to lunch on this idea.

**Comment by WJDDesigns** [comment]
We will be adding active and inactive color per icon and removing from global area. Active and inactive were named that way to correspond with the color being "Active or On" not necessarily the state.

**Comment by WJDDesigns** [comment]
V1.3.1 might be a better way of looking at it. Active is turning the icon on, you can change it per icon now.

**Comment by jayscovill** [comment]
This is great. Thanks!
