### ISSUE TITLE
Changing the card layout in Sections view cause other cards to overlap

### ISSUE THREAD

**Issue by catshapednoodles** [WJDDesigns/Ultra-Vehicle-Card#4]
I quite like the card, so I tried adding it to my Car page, which is a Sections view layout. However, it turns out that this card doesn't work well with Sections unfortunately. Here are two examples:

If you add other cards after this card, they overlap to the point that you can't really read anything on the Ultra Vehicle Card anymore:
![afbeelding](https://github.com/user-attachments/assets/74ee75da-b80f-4648-90c6-226033ff1be3)

In the Edit view you get to see this:
![afbeelding](https://github.com/user-attachments/assets/854aa492-9dc0-417e-84c2-a7e06c4454b2)

I think this points to the Ultra Vehicle Card not properly defining it's dimensions for the Sections view or something. It looks like the card only gets a small default area assigned, which causes the overlap with cards below this card.

**Comment by AlexandreLogist** [comment]
![image](https://github.com/user-attachments/assets/9ffa14b2-0be5-497f-9d8e-b0bc4b7224a7)
I also did some testing, but I am not able to reproduce :)

**Comment by catshapednoodles** [comment]
Oh, I see what caused it. If you try to resize it in the layout tab (see screenshot), then the bug happens. If you then reset the layout, the card doesn't overlap with other cards anymore.
![afbeelding](https://github.com/user-attachments/assets/a7508c17-e60a-48d6-a0d6-5e45fb208ea1)

My issue is fixed for now at least, but I'll change the title to better reflect the bug.

@AlexandreLogist Thanks for trying this out on your end!

**Comment by WJDDesigns** [comment]
I'll see if I can do some CSS wizardry to help with resize, thanks!

**Comment by WJDDesigns** [comment]
So looking in to this we might have a bit of a complicated issue. Horizontally when changing the layout it seems to do pretty well but when vertically changing it has issue and that might be by design since you can't cram all that info in a 1 row 4 column display. This seems to be an issue with other projects as well. I would need to create a view for each setting so that it removed parts of the card as you shrink it to work properly.

**Comment by WJDDesigns** [comment]
We have added ways to show and hide title and also image with height change. This will allow you to then resize the card in sections view.
