### ISSUE TITLE
Feature Request: Color controls

### ISSUE THREAD

**Issue by plaetzchen** [WJDDesigns/Ultra-Vehicle-Card#41]
Thank you for releasing this car, it's great!

It would be cool if I could set custom bar colors for different values, similar to gauges. Like when the SoC is less than 20% it's red, orange when it's below 50% and otherwise blue or something. Right now it's always orange for me when not loading and that seems wrong.

**Comment by WJDDesigns** [comment]
I am hoping to add CSS in to the input area for the colors so you can use https://cssgradient.io/ and drop in your code and it should follow the same principle.
