### ISSUE TITLE
Adding "Charging Status Entity" sensor causes vehicle image to dissapear

### ISSUE THREAD

**Issue by jayscovill** [WJDDesigns/Ultra-Vehicle-Card#45]
Maybe this is just a "me" issue but if I create a fresh card and upload an image it displays correctly.  But as soon as I add an sensor for the "Charging Status Entity" the vehicle image disappears with "no image available".

I was just trying to test with previous versions to see if I could nail down the version it started happening with but It MIGHT be a bug related to whether the vehicle is actually charging as my car JUST stopped charging and now I can't replicate the issue.

**Comment by hornet-dev** [comment]
I ran into the same issue, and I think there's a problem migrating from older versions.

Anyway, I was able to get back to working again:
- Go into Edit mode on the vehicle card
- Choose 'Show Code Editor' in the bottom corner of the card being edited.
- You should now see a bunch of YAML text. Look for 'charging_image_url: ' 
- Paste a valid URL here. I chose the one I use for image_url: in the same YAML

You should now be working again.

**Comment by WJDDesigns** [comment]
This entity's name was changed. I probably could help any updating by having the new field auto add from the old field so it has an entity in there but yeah you could also go in to code and do that.

**Comment by WJDDesigns** [comment]
Should be fixed in V1.4.0 where I add a default image to those fields.
