### ISSUE TITLE
Add an option to treat sensor values "0/1" as "False/True"

### ISSUE THREAD

**Issue by nervous-inhuman** [WJDDesigns/Ultra-Vehicle-Card#46]
Hey there, 

I have a component for my NIU E-Scooter that reports the state of the sensor as an integer:
![image](https://github.com/user-attachments/assets/427ea719-1a50-44d6-b5a6-028185710d7a)

Since Ultra-Vehicle-Card doesn't treat these as "True/False", the "active" states are not displayed properly:
![image](https://github.com/user-attachments/assets/b1133083-b38a-4b89-9c75-156a240e3f4d)
(e.g. IsLocked entity with value of 1 is shown to be inactive in the card)

Could be added as an option when setting up the entities 
![image](https://github.com/user-attachments/assets/7b4ed1f5-91d1-4ce2-8f8d-f714a294c737)

**Comment by WJDDesigns** [comment]
I can just add Active Icons to look for 1 and inactive to look for 0.

**Comment by WJDDesigns** [comment]
Fixed in newest version which will be coming soon!

**Comment by WJDDesigns** [comment]
V1.4.0 should be working now!
