### ISSUE TITLE
"Incorrect" speedometer indication

### ISSUE THREAD

**Issue by nisu66** [WJDDesigns/Ultra-Vehicle-Card#48]
In the card, the speedometer now shows me 2.1 kkm, how can I make it show 2100 km, as happened until 3/4 days ago?

**Comment by WJDDesigns** [comment]
What does that entity say for the unit of measurement?

![image](https://github.com/user-attachments/assets/57aab190-9d62-4066-9594-02adb6e44edb)

**Comment by nisu66** [comment]
![Screenshot_20240818_221453_Home Assistant](https://github.com/user-attachments/assets/4376ad3e-e2c4-43d5-9a9a-033bae2f12a2)
![SmartSelect_20240818_221543_Home Assistant](https://github.com/user-attachments/assets/6f500c43-4c33-4ac2-b15b-f60a74bf186d)
![SmartSelect_20240818_221636_Home Assistant](https://github.com/user-attachments/assets/a5a8d079-8c27-49d8-bffe-06eb18dbe826)

**Comment by WJDDesigns** [comment]
You are not using the latest version, please update and restart HA plus clear cache.

**Comment by nisu66** [comment]
Done,but i have same error
![Uploading Screenshot_20240818_225832_Home Assistant.jpg…]()

**Comment by nisu66** [comment]
Done, but i have same errore :-(
![Screenshot_20240818_225832_Home Assistant](https://github.com/user-attachments/assets/db710d0d-ffec-41be-9365-6f4bbb87f919)

**Comment by nisu66** [comment]
Done, but i have same errore :-(
but I only noticed now that the km / miles option has disappeared.....
![Screenshot_20240818_225832_Home Assistant](https://github.com/user-attachments/assets/c86d7bdf-3eb7-4182-96e9-c80c722ddc55)

**Comment by WJDDesigns** [comment]
Please clear the cache. It should now use the Unit of Measurement on the card instead of choosing mi/km it will just use that.

**Comment by MartinAirN** [comment]
As far as I can find the "FormatRange" function is called for all mileages:
```
if (mileageEntity) {
    const value = parseFloat(mileageEntity.state);
    const unit = mileageEntity.attributes.unit_of_measurement || '';
    mileage = this._formatRange(value, unit);
  }
```
```
_formatRange(value, unit) {
  const numValue = parseFloat(value);
  if (isNaN(numValue)) return value;
  
  const formattedValue = this._formatNumberWithCommas(Math.round(numValue));
  
  if (unit === 'km' && numValue > 1000) {
    return `${this._formatNumberWithCommas(Math.round(numValue / 100) / 10)} k${unit}`;
  } else {
    return `${formattedValue} ${unit}`;
  }
}
```

**Comment by WJDDesigns** [comment]
Correct we format ranges to round up as well as you see unit of measurement being added.

**Comment by MartinAirN** [comment]
That seems to be the request by @nisu66, that you can show without that formatting.

**Comment by WJDDesigns** [comment]
Yeah we will clean that up, we had another user ask for rounding up but we will then ask them to use a helper to keep it raw. Maybe next minor release.

**Comment by WJDDesigns** [comment]
We are now rounding up if the milage or range has a decimal since this will look much better either way. The range and milage should be not touched other than that in V1.5.1
