### ISSUE TITLE
Please don't mess with case on status entitity

### ISSUE THREAD

**Issue by altrnate32** [WJDDesigns/Ultra-Vehicle-Card#49]
Hi,

I love your card. It is very nice, I created my own with an image card, but this is so much better.

One request though: please remove the code that transforms the state of the vehicle status entity to lowercase, then splits it by _ and makes all bits uppercase. I think a card displaying info should not mess with capitalisation. The user can change it through a template sensor if needed.

My status entity displays for example: Charging | Ending in 40 minutes | 11 kW

When passes through your filter it gets messed up.

I can fork your repo and easily fix it, but I think it will also benefit other users (as the display layer should not mess with the content)

**Comment by WJDDesigns** [comment]
Yeah it's fixed in newest update coming.

**Comment by altrnate32** [comment]
Hero!

**Comment by WJDDesigns** [comment]
V1.4.0 Fixed this and displays the raw state. :)
