### ISSUE TITLE
[Bug]: Image Entity not displayed

### ISSUE THREAD

**Issue by MartinAirN** [WJDDesigns/Ultra-Vehicle-Card#51]
With version 1.4.0 the image entity is no longer displayed and a default image ([lambo](https://github.com/user-attachments/assets/4ef72288-5ee9-4fa6-b2f3-c34c4160cf42)) is shown instead.

**Comment by WJDDesigns** [comment]
You might have a cached issue as I just checked and was able to add an entity as an image and save it without any issues.

**Comment by MartinAirN** [comment]
I thought the same, hence I tried it on Android with a cleared cache and on windows in a private browser window.

![image](https://github.com/user-attachments/assets/da9fde34-d4ef-45c5-ae99-d7ff44042466)
![image](https://github.com/user-attachments/assets/76b94463-3c29-43e5-ab60-713f1c79ea1d)

**Comment by WJDDesigns** [comment]
> Agreed, I see the same thing.
> 
> 
> 
> ```
> 
> _renderVehicleImage() {
> 
>   const isCharging = this._isCharging(this.config.charging_status_entity ? this.hass.states[this.config.charging_status_entity] : null);
> 
>   const imageUrl = isCharging ? this.config.charging_image_url : this.config.image_url;
> 
> 
> 
>   return html`
> 
>     <div class="vehicle-image-container">
> 
>       <img class="vehicle-image" src="${imageUrl}" alt="Vehicle Image" @error="${this._handleImageError}">
> 
>     </div>
> 
>   `;
> 
> }
> 
> ```
> 
> 
> 
> I don't see any reference to the entity in the `_renderVehicleImage` method.

So you are saying you can not add an entity as an image at all, main or charging?

**Comment by lxalln** [comment]
Correct, this is what I see after saving and opening the config editor:

![image](https://github.com/user-attachments/assets/5566f628-8e7c-4dd5-bfe2-543dbc24d3c0)

**Comment by WJDDesigns** [comment]
Hmm and that doesn't look like a Volvo, I see...

When looking in console you should see a tag for my card and the version number, what is it?

**Comment by lxalln** [comment]
Here you go: 

![image](https://github.com/user-attachments/assets/d84d353a-3c4f-495a-9139-6a4be02c4377)

I noticed that error too, that might be related.

**Comment by WJDDesigns** [comment]
Fixed with latest release.
