### ISSUE TITLE
Feature Request: Support also entity attributes as source value.

### ISSUE THREAD

**Issue by dianlight** [WJDDesigns/Ultra-Vehicle-Card#53]
Hi,
 nice card. It is very useful but in mu case some of the display data come from entity attributes and not from value/state.
Is possible to support source also from attributes or support template as source?

For example the charge of the EV Battery in my case is:
{{ sensor.fordpass_elvehcharging.attributes.BatteryCharge }}

Regards
L.

**Comment by WJDDesigns** [comment]
It should work, mine has attributes and it looks for charging, is charging and so on. What is your attribute?

**Comment by WJDDesigns** [comment]
V1.5.2 should introduce this, please let us know if not.

**Comment by dianlight** [comment]
Hi, I install the v1.5.3 but I don't se in doc on the UI any reference how set the attribute to read. Can you explain how test?

L.
