### ISSUE TITLE
Still issue with Icon Grid and clicking to icons

### ISSUE THREAD

**Issue by fuchsbau123** [WJDDesigns/Ultra-Vehicle-Card#55]
What I did was add trigger which will work for Automations (if needed, look I get it why would you want to trigger an automation to happen if it's uhhh automated) scripts, scenes or any entity that is in the entity picker that needs triggered vs toggled.

_Originally posted by @WJDDesigns in https://github.com/WJDDesigns/Ultra-Vehicle-Card/issues/47#issuecomment-2295374685_
       
I installed the latest version 1.5.1. 
I am still see only "automation" and no "trigger" in the "Icon Grid" section under "Interaction".
If I click to the icon the automation selected under "Interaction" is still not executed.
I cannot see any script or scenes in the entity picker...

![image](https://github.com/user-attachments/assets/72e5edc8-58ed-43f9-8102-dd565fa51c22)

**Comment by WJDDesigns** [comment]
V1.5.2 should help you as it might be a cache issue since we did add that as an option. Update/Restart/Clear Cache
