### ISSUE TITLE
Sill issue with image entity not displayed

### ISSUE THREAD

**Issue by yuckypants** [WJDDesigns/Ultra-Vehicle-Card#56]
I read over the tickets that were closed yesterday for the image displaying a lambo instead of the vehicle, and it appears to still be happening, as well as common_away. I verified that I'm running 1.5.1 and have also verified that it's not a caching issue, I opened in a separate browser, as well as private mode. 

I also tried to upload my own image to circumvent the online grab, but it's not working either.

**Comment by yuckypants** [comment]
uh. nevermind. it's working now. I have no idea what changed...

**Comment by yuckypants** [comment]
Sorry, closed since it appeared to be working, but realized the car stopped charging which is why the correct image displayed again.

**Comment by Potyike** [comment]
Same here. Cleared cache, tried different browser but still red lambo. Even if i set both the main and charge image to 'none' still showing the red lambo.

**Comment by WJDDesigns** [comment]
V1.5.2 should have this fixed, if not let us know.
