### ISSUE TITLE
Custom element doesn't exist: ultra-vehicle-card

### ISSUE THREAD

**Issue by TheLion** [WJDDesigns/Ultra-Vehicle-Card#59]
Hi,

Not sure if it is due to the latest Ultra Vehicle Card update, or due to the HACS update to 2.0, but in the HA app (on iOS) the error "Custom element doesn't exist: ultra-vehicle-card" is displayed in stead of the card. 

In a browser, both on Windows and iOS it works just fine.

Not sure what to look for or check.

Any suggestions?

**Comment by WJDDesigns** [comment]
What version are you running? Should be 1.5.3, restarting HA and clear cache.

**Comment by TheLion** [comment]
It’s 1.5.3. HA restarted. Not sure how to clear the cache in the HA app though. 
Same issue. Only in HA app.

**Comment by WJDDesigns** [comment]
> It’s 1.5.3. HA restarted. Not sure how to clear the cache in the HA app though. 
> 
> Same issue. Only in HA app.

The app when first load has an icon for a cog wheel (iOS not sure on Android) click it and go to Debugging and clear front end cache. 

Are you using CDN for SSL too?

**Comment by TheLion** [comment]
Found it! Didn't solve the issue initially. 

No, connecting from local wifi directly to HA with own SSL certificate. 

When connected through cellular with Nabu Casa forward, it does work in the app. 

After switching back to wifi, it also works correctly.

Strange.

**Comment by yuckypants** [comment]
Having the same issue. Cleared cache, tried in several different browsers, no change. Even removed and reinstalled teh integration. Strangely, it did not recreate the resource...

My resources all follow the same syntax: /hacsfiles/<folder>/<path>, but /local/ultra-vehicle-card.js is giving me the same result, no joy.

**Comment by WJDDesigns** [comment]
It really comes down to caching issues. What I suggest is to manually download the files and replace them inside Ultra-Vehicle-Card directory. I'm not able to replicate this at all, since I have no CDN, fully local and have new installs for testing and still have the same result of it working.

**Comment by yuckypants** [comment]
Unfortunately, no change, still can't load the card. I verified the cache was cleared and used a completely different browser that has never accessed HA. I also cannot load it on my mobile device, so I think the error is genuine in that HA cannot see the card. 

I opened up dev options on Chrome to inspect the element and got this: 

when configured with /hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card.js, the error is: Uncaught SyntaxError: The requested module './version.js' does not provide an export named 'setVersion' (at ultra-vehicle-card.js?hacstag=833206795153:2:19)

and when configured with /local/ultra-vehicle-card.js, I get a 404 (Not Found). 

I always run my resources as /hacsfiles/*, and this hasn't changed from when it was working.

**Comment by yuckypants** [comment]
ahhh - looks like I got it - it's /local/community/Ultra-Vehicle-Card/ultra-vehicle-card.js

Not sure why the change, but i'm also still running the old hacs, so if this is due to the updates, this could explain a lot.

**Comment by yuckypants** [comment]
Sorry for the constant replies, but I'm finding things out as I go. Although it's now displaying properly, I'm getting an error in HACS that says the card isn't loaded. I'm sure it's because of the resource path I have defined, which is not normal. 

Also, maybe should be a separate issue, but I have 2 cars I'm tracking and the images are slightly different sized. Now the cards are no longer equally sized. I wonder if it's possible to add a ratio or dimensions or even revert what the change was that allows this?

**Comment by Auka84** [comment]
Hi

I have the same issue after i updated my HA to 13.1

HACS is not yet updated to 2.0

How did you resolve the issue @yuckypants  ?

I have this

![Capture d’écran 2024-08-22 à 07 49 23](https://github.com/user-attachments/assets/3329b8ba-7d86-4a4b-8af9-de0129f42cc1)

thx

**Comment by MartinAirN** [comment]
It seems that the fix I implemented to prevent this in the future caused this for those upgrading to the fixed version.

The `version.js` file is not updated, whilst others are. Causing the entire card to fail.

So for those experiencing this, this should be the last time you see it. To fix it make sure the cache is completely cleared, on the client side and any possible proxy inbetween.

Easiest fix on deskop:
- navigate to `https://[ha url]/hacsfiles/Ultra-Vehicle-Card/version.js
- Ctrl + F5
- Re-open HA
- Ctrl + F5 & F5 (Again)

Android:
- Go to App-Info for HA (most phones this is `long press` on the app icon)
- Storage & Cache
- Clear Cache

**Comment by Auka84** [comment]
thx @MartinAirN   It works for me :)

**Comment by MJHeijster** [comment]
On my end I fixed it by setting cloudflare to development mode (to disable cache) and clearing the cache from the browser and app. I also have the new options that I've been seeing in the changelog (like changing the icon position) that I haven't had before.

**Comment by MartinAirN** [comment]
@WJDDesigns I will add a new PR to fix this. Its a simple fix, but requires a tiny bit of work on your end every time the `version.js` file needs a change.

**Comment by WJDDesigns** [comment]
I had implemented a fix like this previously with the same version at the end but got caught in to the same issue that I would have to manually change the version for each file versus just one central location which I don't like, that's why I didn't do this in the first place.

**Comment by mattdevo1** [comment]
I'm having the same issue. V1.53, HACS still on 1.34. Restarted HA and cleared cache (iOS app). Still broken.

**Comment by yuckypants** [comment]
Updated to v 1.5.6 and looks good! Thanks and great work with this card!

**Comment by WJDDesigns** [comment]
I'm glad you got it working and hung around to give it a chance! Now spread the word haha!

**Comment by plains203** [comment]
Fixed on my install by uninstalling the card and reinstalling
