### ISSUE TITLE
Fuel and range only shown in EV mode

### ISSUE THREAD

**Issue by jedifindtrick** [WJDDesigns/Ultra-Vehicle-Card#60]
As title says, the fuel and range is only shown in EV mode, not fuel. 
```
title: Yngve
image_url: >-
vehicle_type: Fuel
unit_type: km
level_entity: sensor.ysn705_fuel_level
range_entity: sensor.ysn705_range
charging_status_entity: sensor.ysn705_fuel_level
location_entity: device_tracker.ysn705_position
mileage_entity: sensor.ysn705_odometer
show_level: true
show_range: true
show_location: true
show_mileage: true
icon_grid_entities: []
custom_icons: {}
type: custom:ultra-vehicle-card

```
![image](https://github.com/user-attachments/assets/78e0fa53-e7fc-4b5f-8a67-3277d718b524)
![image](https://github.com/user-attachments/assets/ce328418-2318-4523-8bf2-e88fc11b963c)

**Comment by WJDDesigns** [comment]
I can't replicate this error, please download the latest version, restart Home Assistant and clear cache. Let me know if this is still an issue.
