### ISSUE TITLE
Not showing full mileage

### ISSUE THREAD

**Issue by NickBouwhuis** [WJDDesigns/Ultra-Vehicle-Card#68]
Hi,

My card looks like this:
<img width="504" alt="image" src="https://github.com/user-attachments/assets/d993b5b1-6e3b-4616-a0bd-a181059106b3">

While I'd like it to show the full mileage (in my case 141,351 km)
<img width="562" alt="image" src="https://github.com/user-attachments/assets/e4da2df7-7348-462c-a3a4-c316fe4a6992">

I'm not sure why mine does this. Other examples seem to show the full mileage.

**Comment by WJDDesigns** [comment]
What version are you running?

**Comment by NickBouwhuis** [comment]
I'm currently running 1.4.0. But upon checking my version I saw that there is an update. Will install and report back.

**Comment by NickBouwhuis** [comment]
That's better. Thanks! :-)

![image](https://github.com/user-attachments/assets/20cd83db-c030-4413-8e95-5211e6ad12d1)
