### ISSUE TITLE
Broken after HACS update

### ISSUE THREAD

**Issue by dennisbrouwer91** [WJDDesigns/Ultra-Vehicle-Card#69]
Hi,

After the big HACS upgrade, the add-on stopped working : 
<img width="480" alt="image" src="https://github.com/user-attachments/assets/5e786e8e-527f-4afc-9908-d39d081d908a">

Tried reinstalling, but that doesn't fix the issue.

**Comment by didvids** [comment]
Having the same issue trying to load in Firefox desktop browser.

Oddly, still works in Android App, desktop Mullvad browser, mobile Firefox browser.

**Comment by WJDDesigns** [comment]
I have it working on my own install and can't replicate. You could have caching issues. Please install the newest build, restart Home Assistant and clear cache. Always try in an incognito window or different browser to see if caching is happening. If you use Chrome I highly recommend the Clear Cache extension which does a hard reset of cache. If you are using CloudFlare as a CDN you will need to wait or reset the cache there.

**Comment by dennisbrouwer91** [comment]
You're right, it's working in incognito (Chrome) so it's a very, very weird caching issue!

**Comment by WJDDesigns** [comment]
Caching is always the issue ;) Thanks for reaching out!!!

**Comment by dennisbrouwer91** [comment]
I just cleared the CloudFlare cache, but that didn't solve it. Do you know which file i should be looking for in Developer Tools in Chrome to check where it's coming from?

**Comment by dennisbrouwer91** [comment]
Okay, if you hard clear the cache in Chrome, it starts working again!

**Comment by didvids** [comment]
I've tried clearing the cache etc. Still no luck in Firefox Desktop 129.0.2

Following errors from the console:

Module source URI is not allowed in this document: “https://unpkg.com/lit-element@2.4.0/lit-element.js?module”.

Uncaught (in promise) https://homeassistant.hmsrv.xyz/local/community/Ultra-Vehicle-Card/ultra-vehicle-card.js

Loading failed for the module with source “https://homeassistant.hmsrv.xyz/local/community/Ultra-Vehicle-Card/version.js?v=3”.

The resource at “https://homeassistant.hmsrv.xyz/static/fonts/roboto/Roboto-Regular.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.

The resource at “https://homeassistant.hmsrv.xyz/static/fonts/roboto/Roboto-Medium.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly..

**Comment by WJDDesigns** [comment]
Uncaught (in promise) https://homeassistant.hmsrv.xyz/local/community/Ultra-Vehicle-Card/ultra-vehicle-card.js

Loading failed for the module with source “https://homeassistant.hmsrv.xyz/local/community/Ultra-Vehicle-Card/version.js?v=3”.

These two are from my card but I can tell they aren't updated to the latest and are pulling up not the same version of files. If you are using Cloudflare CDN for SSL it probably is still cached. You must clear all caches.

**Comment by didvids** [comment]
> If you are using Cloudflare CDN for SSL it probably is still cached

No cloudflare. I'm using Let's Encrypt.

> You must clear all caches.

Cleared the all caches in Firefox. Downloaded a fresh install of Chrome, just for a test. No good.

**Comment by WJDDesigns** [comment]
You could always try downloading the latest package from GitHub release https://github.com/WJDDesigns/Ultra-Vehicle-Card/releases/tag/1.5.8

Overwrite the files in the HACs folder where they are located for your install and then restart HA/Clear Cache. You have mismatched files.

**Comment by didvids** [comment]
I have tried purging the original installation and reinstalling using HACS repository. Same issue.

Purged again. Attempted manual install using the instructions, card doesn't appear at all.

Have tried clearing caches in both attempts.

**Comment by WJDDesigns** [comment]
Well soon I'll be putting up a new update and you can see if updating fixes things.
