### ISSUE TITLE
Actionable grid icons

### ISSUE THREAD

**Issue by sibbl** [WJDDesigns/Ultra-Vehicle-Card#7]
Thanks for the awesome card!

I'd love to be able to click the icons to interact with them, i.e. to turn on a/c or stop charging.

It doesn't need to trigger the actions directly by clicking the icon but at least open the entity dialog when clicking them.

**Comment by WJDDesigns** [comment]
Working on a link/click button to define one. Thanks for the suggestion!

**Comment by sanchosk** [comment]
It would be great if I can also select a "device" to point to when I click on the vehicle image.
