### ISSUE TITLE
Feature Request: rules to define active per button

### ISSUE THREAD

**Issue by knuckleheadsmiff** [WJDDesigns/Ultra-Vehicle-Card#73]
Buttons allowing more conditions to show active. (A work around for now is to create a template sensor I suppose.)

When my car for example is charging or plugged I’d like the button to be green/active. Being able to have simple rules for active state per button would make this easier. 

For my car for example the states for charging are ‘charging’ and ‘disconnected’ when plugged initially is ‘idle ‘ and ‘charging’

currently I’m not sure what constitutes ‘active’

**Comment by WJDDesigns** [comment]
Charging is an Active word so you should see that as active in the icon area. I'm not sure how we will be adding conditional logic in as templates are already part of HA. There's a lot to think about and how or if we want to extend this and make things more complicated.

**Comment by knuckleheadsmiff** [comment]
First, thanks for this card! Second, so if charging is an active word then why is this not showing as active?
![IMG_0816](https://github.com/user-attachments/assets/eede9d13-33e4-4891-817d-14b3cf9ddd90)
![IMG_0817](https://github.com/user-attachments/assets/723c0396-c617-47bb-9e5c-b24c3213c3a7)
![IMG_0815](https://github.com/user-attachments/assets/821113be-33e4-464c-994a-01323fd8bb47)

**Comment by WJDDesigns** [comment]
Could be a bug, I can look into it! Also thanks for the good comments!!

**Comment by knuckleheadsmiff** [comment]
That, same would be true with the connected icon.

**Comment by WJDDesigns** [comment]
<img width="464" alt="Screenshot 2024-08-23 at 8 50 59 PM" src="https://github.com/user-attachments/assets/e9564215-8019-4f28-9c06-f219f5f41714">

Check newest release and let me know if the icons are showing active.

**Comment by knuckleheadsmiff** [comment]
Humm not seeing a difference. I only tested the connect status as my car stopped charging.  I also rebooted after installing. 

![IMG_4801](https://github.com/user-attachments/assets/faac23f1-1be5-4bcf-925b-c3ac45772eaa)
![IMG_4799](https://github.com/user-attachments/assets/3916d972-54c4-4541-9fdc-4a4ce2134bcd)
![IMG_4800](https://github.com/user-attachments/assets/57b9b784-6f77-4ccd-a9ec-f88a7c929c62)

**Comment by WJDDesigns** [comment]
You might be cached. Please update, restart Home Assistant and the major important part is clear cache. If you are using a CDN like cloudflare clear cache there. You can also try an incognito window in your browser to test changes.

**Comment by WJDDesigns** [comment]
Also it shows decimal points and if you have formatting turned on in the config it should not show decimal points.

**Comment by knuckleheadsmiff** [comment]
Humm. It’s running 1.5.8 and I’ve tried incognito mode, restarting, redownloading ….

My wife is calling me for dinner so I can try more later.

**Comment by knuckleheadsmiff** [comment]
It looks like I'm running and have downloaded the correct version but for example I not seeing the number rounding? Very odd (I see your rounding changes in the file.)

<img width="1023" alt="Screenshot 2024-08-24 at 10 48 41 AM" src="https://github.com/user-attachments/assets/05e55f28-432e-4aaa-8e76-4eb9fdf9e130">

**Comment by WJDDesigns** [comment]
Do you have the format switch on? What does your sensor output look like in n the settings?

**Comment by knuckleheadsmiff** [comment]
I do now! And it’s now rounding. I’ll check the plugged in status again after lunch. 

Note the description for the format switch seems to be missing. 
![IMG_0819](https://github.com/user-attachments/assets/f650d74d-9a35-4f4d-a1fc-e1dde1b6f14d)

**Comment by WJDDesigns** [comment]
> I do now! And it’s now rounding. I’ll check the plugged in status again after lunch. 
> 
> 
> 
> Note the description for the format switch seems to be missing. 
> 
> ![IMG_0819](https://github.com/user-attachments/assets/f650d74d-9a35-4f4d-a1fc-e1dde1b6f14d)
> 
> 

![image](https://github.com/user-attachments/assets/062c3c87-9dfa-4d64-951c-4dd7944309a5)

The text is in the translation so you could be still getting old versioning. If you look in either English (en) files you will see that it does have these items in there. What language are you using?

**Comment by knuckleheadsmiff** [comment]
OK, I went to my computer, instead of my iPad. I'm seeing the description and then formatting switch is working. But I'm still not seeing the active colors for charging.
<img width="1010" alt="Screenshot 2024-08-24 at 1 26 32 PM" src="https://github.com/user-attachments/assets/0918a51e-f8a7-413f-a74a-3d8d055ad971">

**Comment by WJDDesigns** [comment]
Do you have Discord we can chat over here https://discord.gg/jxWefW6c
