### ISSUE TITLE
1.5.8 : remaining range in km too many decimals.

### ISSUE THREAD

**Issue by ThaReaper** [WJDDesigns/Ultra-Vehicle-Card#75]
when i display the remaining range of my EVs in KMs, there are 6 decimals. 

![image](https://github.com/user-attachments/assets/b37bd00a-b05d-4c08-b087-e349075c486d)

**Comment by mattdevo1** [comment]
You can change the number of decimals displayed in the entity config. This is not an issue related to the card. 

![image](https://github.com/user-attachments/assets/90bddfa5-b1cd-49cf-8944-c04180879a84)

**Comment by WJDDesigns** [comment]
Also in the newest update we are correcting this regardless if format entities is on.

**Comment by ThaReaper** [comment]
Hi, the entity config was already configured to show no decimals, so i dont understand why it would display 6 decimals then, and 2 for my other car.

**Comment by ThaReaper** [comment]
> Have you updated to the newest version? You should not see trailing zeros. Make sure to restart Home Assistant and clear cache everywhere.

I have just updated to 1.5.9, restarted HA, and cleared browser cache, and the problem persists:

![image](https://github.com/user-attachments/assets/04046f5f-7919-46b8-a710-bdc018c9ac69)

**Comment by ThaReaper** [comment]
Nope! that did the trick indeed! 
weirdly, before, when i changed the range entity to "default" number of decimals, then the number of decimals changed to 2. all other options changed it to a "shitton"

**Comment by WJDDesigns** [comment]
I have no clue what happened previously but it looks like the formatter fixed your main issue right?

**Comment by ThaReaper** [comment]
> I have no clue what happened previously but it looks like the formatter fixed your main issue right?

it did. no more problems now.

**Comment by MJHeijster** [comment]
Hmm mine changes 290.6 km to 2906km with 1.5.9 with default precision.  
![image](https://github.com/user-attachments/assets/9a7aad2e-37dc-44c1-ae41-5eef98f22b43)

![image](https://github.com/user-attachments/assets/51079791-5b02-4dde-9bce-cd05a16f8884)

Setting the default precision to 291 will result in me having 291 km of range, setting it to 290,631433 would be the dream of every driver. 
![image](https://github.com/user-attachments/assets/6e6298a0-0da8-419d-a94a-1c010ae6aaf6)

**Comment by WJDDesigns** [comment]
Number separators vary by locale. In continental Europe, for example, the most common convention is that the comma marks the decimal place and that large numbers are separated into powers of 3 (thousands) with a space.
In the U.S., the convention has long been that a period marks the decimal and that commas separate large numbers. In South Asia, commas are used for separating large numbers. So, depending on where you are in the world, the same number could be represented as

10 000 000,05
10,000,000.05
1,00,00,000.05

So this means we still need to add that logic in. I'm American and it's been difficult creating something that works for each locale. I'm hoping I can figure out a way to do so..

**Comment by MJHeijster** [comment]
Ah, I just saw the odometer, now my car only has 48 km on it 🗡️ 

Hope there's a proper library handling this.

**Comment by WJDDesigns** [comment]
I hope so too, all we can do it hope that the developer fixes this... Wait, that's me... I've been busy rewriting the code and adding some cool stuff so give me a second :)

**Comment by MJHeijster** [comment]
Nothing is going wrong, it's only a visual issue, so it is what it is :)

I've been impressed with the speed of changes as a develop myself. Python is totally not my thing though, so can't help there 🕺

**Comment by WJDDesigns** [comment]
Try V1.6.0-beta3 and let me know if it words the way it is intended.

**Comment by WJDDesigns** [comment]
I programmed it to react to the locale you are in, so you have format on and your language selected? If so what are your settings?

**Comment by MJHeijster** [comment]
![image](https://github.com/user-attachments/assets/aee82da4-18b3-46f0-8804-99404f47bfc0)

**Comment by elmr91** [comment]
Same problem here with latest stable release. Range is wrongly displayed:  
![image](https://github.com/user-attachments/assets/e78fb3ea-3a36-48c6-ac8c-7ae350710a1f)
Range is 288 km 

Displayed correctly but without unit if formatting is off:
![image](https://github.com/user-attachments/assets/8a2fadb7-b250-4036-b25b-b466ed0c68a5)
But wrongly displayed if formatting is on: 
![image](https://github.com/user-attachments/assets/1b77e13f-d03b-4eda-826a-c67f9554290a)

**Comment by WJDDesigns** [comment]
Good news! This should be fixed next version, if it is not then you can get your pitchforks out and start a meeting on what to do from there.

**Comment by WJDDesigns** [comment]
Has it been fixed in the new update 1.6.0?

**Comment by MJHeijster** [comment]
Nope, going to purchase a pitchfork. 
![image](https://github.com/user-attachments/assets/e53dd4dd-a506-4ae5-b3a1-36220022c7e1)
odometer and range are wrong.

**Comment by MJHeijster** [comment]
Can confirm that this issue is fixed in the 1.6.1-beta-1 release. 
![image](https://github.com/user-attachments/assets/1c1816b6-a890-4938-92d3-fc5e612ae636)
