### ISSUE TITLE
Card sizing issue

### ISSUE THREAD

**Issue by yuckypants** [WJDDesigns/Ultra-Vehicle-Card#77]
Early iterations of the integration, cards were equally sized (1.4.0 worked properly). Since the last handful of updates, it appears to be driven by the size of the photo. Both of these photos are identical in size (I cropped to be both equal to 1819x795 pixels); however, as you can see, the card on the right is just a bit larger. 

I'm at a point that it's impossible to make this image any smaller whatsoever. I can make the photo smaller, but it has no effect and it's driving my OCD mad. 

I'm running v 1.5.8, too. I also want to say that your card is freaking amazing, easily one of the best looking here, and I love it. I found it on Reddit about a month ago and have been sharing with so many others, as well. 

![Screenshot 2024-08-25 101037](https://github.com/user-attachments/assets/6453c3fe-0874-4899-9a93-3676e00c4084)

**Comment by WJDDesigns** [comment]
We are adding image height field for adjustments. Width will be auto.

**Comment by yuckypants** [comment]
AWESOME. I will keep my eyes peeled. THanks again for the great work (and for being SO responsive)!
