### ISSUE TITLE
Feature Request: AdBlue Bar

### ISSUE THREAD

**Issue by Funkybeatz15** [WJDDesigns/Ultra-Vehicle-Card#80]
Please add a AdBlue Bar :)

**Comment by WJDDesigns** [comment]
Does this have a percentage or is it just mileage left?

**Comment by PottiMc** [comment]
For Skoda CarConnect it is "Mileage left" but in good units, like kilometers and so ;)

**Comment by WJDDesigns** [comment]
I am not sure if we are adding AdBlue or not and if so how long it will take to be placed in. What you could do is choose Hybrid and then make a template to convert the mileage left to 1-100 to use in to the card as battery.
