### ISSUE TITLE
Feature Request: Dates in kilometers and/or days

### ISSUE THREAD

**Issue by Funkybeatz15** [WJDDesigns/Ultra-Vehicle-Card#81]
For example: 

Inspection Dates (Oil) in Kilometers and Days
Service Dates in Kilometers and Days

**Comment by Funkybeatz15** [comment]
![1](https://github.com/user-attachments/assets/94691d07-1928-4e93-baa4-69a348a90626)
![2](https://github.com/user-attachments/assets/4f81fccd-5ba5-40cd-b8c9-8b89b62e2e5d)

Want to display this in card

**Comment by WJDDesigns** [comment]
You can choose the Oil Inspection Days entity then add an oil icon and use the label to show the days or distance whatever you need. We do not have plans on adding two labels at this time.
