### ISSUE TITLE
Can't change title

### ISSUE THREAD

**Issue by nyr3188** [WJDDesigns/Ultra-Vehicle-Card#83]
If I try to change the title of the car away from "My Vehicle" it just changes to "false." If I try to edit in YAML it crashes the Chrome tab. I have also tried to edit it in the android app without success

**Comment by WJDDesigns** [comment]
Try V1.6.0-beta3 and let me know if this is fixed.

**Comment by Abeilard14** [comment]
I had the same issue, fixed successfully with V1.6.0-beta3

**Comment by nyr3188** [comment]
> Try V1.6.0-beta3 and let me know if this is fixed.

Just got the time to try it out and, like Abeilard14 said, the issue is fixed by using v1.6.0-beta3. Thanks for looking into it.
