### ISSUE TITLE
Language Norwegian 

### ISSUE THREAD

**Issue by Amokk123** [WJDDesigns/Ultra-Vehicle-Card#85]
I have a question:
IS it possible to get Norwegian language to the card?

**Comment by WJDDesigns** [comment]
Added in V1.6.0-beta3 - soon to public release.

**Comment by Amokk123** [comment]
Hello sir.. I love this EV card.. 
I have tried the V1.6.0-beta 3and 4 . But i still not get Norwegian language to appear. (I see the no-language, in the language folder). I have deleted cache several time. Tried another browse, first time show this card, but same result. I have uninstalled the card, rebooted HA. Installed Beta once again, but no luck. Do you know what causes this??
