### ISSUE TITLE
1.6.02-beta2: Odometer value destroyed

### ISSUE THREAD

**Issue by Funkybeatz15** [WJDDesigns/Ultra-Vehicle-Card#86]
Format Entities in 1.6.0-beta2 destroys my displayed odometer value:

with:
![1](https://github.com/user-attachments/assets/c01edd1e-a619-44cd-9119-4dae8c6820e2)

without:
![2](https://github.com/user-attachments/assets/bb65b754-bd7e-4cd0-b8c1-e78b730ad8ff)

**Comment by PottiMc** [comment]
Same for me in 1.5.9

**Comment by WJDDesigns** [comment]
We are working on different locals and the way , and . are used.

**Comment by WJDDesigns** [comment]
Also Betas are not for the public. We specifically are adding and fixing parts when knowing some parts aren't working as we build. If you grab a beta know you are testing at your own risk 😃

**Comment by WJDDesigns** [comment]
Try V1.6.0-beta3 to see if this is fixed.

**Comment by PottiMc** [comment]
It is fixed, thank you!
