### ISSUE TITLE
1.5.9: Can't click extra icons

### ISSUE THREAD

**Issue by PottiMc** [WJDDesigns/Ultra-Vehicle-Card#88]
I am not able to click the extra icons anymore. HA restarted, version 2024.8.3, cache cleared.

![image](https://github.com/user-attachments/assets/7326d223-5d29-4ced-85c7-9f9f9146dd61)

**Comment by WJDDesigns** [comment]
Did you add an interaction to these icons?

**Comment by PottiMc** [comment]
Wow, that was easy. Somehow the entries got deleted or something. Changed it, now it works again.
