### ISSUE TITLE
Custom element doesn't exist: ultra-vehicle-card

### ISSUE THREAD

**Issue by rw377** [WJDDesigns/Ultra-Vehicle-Card#89]
I have two wall-mounted Amazon Fire tablets, both of which are used to show the Ultra card. This has been working well when I was on (I believe) version 1.5.1. I of the card. I recently upgraded to 1.5.7 and I started getting an error where both cards were on lovelace: "Custom element doesn't exist: ultra-vehicle card"
![image](https://github.com/user-attachments/assets/b6aa0746-ea6e-4cec-9253-7a9c0a810a26)

This issue doesn't happen on my Android phone or through my PC web browser which makes this a bit confusing.  But it is odd it's happening to both tablets at the same time and after a card update. 

A few things I have tried:
-Cleared cache and rebooted both tablets
-Rebooted Home Assistant
-Upgrading the card to the latest version (currently 1.5.9)
-Creating a new dashboard with an empty Ultra card
-Verified the card is showing up in Dashboard > Resources

Running:
HA Core 2024.8.2
HA OS 12.3

**Comment by WJDDesigns** [comment]
Try V1.6.0-beta3 and test if this is fixed.

**Comment by rw377** [comment]
> Try V1.6.0-beta3 and test if this is fixed.

Still occurring after installing V1.6.0-beta3, thank you for looking into this though, I appreciate it.  I installed HACS to the latest 2.0 version to see if that made any difference but it did not. I did try re-downloading 1.5.1 and it does work again for what it's worth. I think I am okay with keeping at this version for now though. 

Oddly enough, one tablet is working fine now and the other still isn't. The one that isn't does have a popup when opening FullyKiosk that says "Be aware of outdated Android webview, current version 75". I'm not sure what Webview is but that may have something to do with it? I think I will need to try and update this but at least one tablet is working

**Comment by PottiMc** [comment]
Did you really clear your browser cache? Please check this. Or even try to download (just for testing of course) a totally different browser app.

**Comment by WJDDesigns** [comment]
I really think this issue is cache related since it should work on both and something is getting hung up.

**Comment by rw377** [comment]
> Did you really clear your browser cache? Please check this. Or even try to download (just for testing of course) a totally different browser app.

Yes they both use Fully Kiosk and I cleared the cache on both tablets to the point where it logged out of Home Assistant, reset the theme settings, etc. At this point running card version 1.5.1 and both tablets are working so I will leave it like this. Down the road i may try updating again but it meets my purposes for now. I think this can be closed but thanks for the help. I will re-open if issue persists with later upgrade

**Comment by sNiXx** [comment]
I think I found the root cause of this one. I stumbled over it myself and was really confused why I could not see the custom card at all. In my case, this was related to uBlock Origin blocking 3rd party scripts from unpkg.com.
