### ISSUE TITLE
Wrong Vehicle Image

### ISSUE THREAD

**Issue by joelevi** [WJDDesigns/Ultra-Vehicle-Card#90]
When  **charging_status_entity** is supplied (either via the graphic editor or via yaml), the default vehicle image is displayed (not the custom image provided).

Manually deleting **charging_status_entity** from the yaml fixes the behavior.

**Comment by WJDDesigns** [comment]
Try V1.6.0-beta3 and let me know if it is fixed.

**Comment by WJDDesigns** [comment]
Can't replicate here, let me know if it still is an issue.
