### ISSUE TITLE
Feature request - image side-by-side with header text

### ISSUE THREAD

**Issue by baf** [WJDDesigns/Ultra-Vehicle-Card#94]
Thanks for the great card and the rapid pace of development. Is it possible to create a display mode that conserves vertical space a bit by placing a (smaller) vehicle image to the left of the header text and location/mileage? I know that I can remove the image entirely but thought it would look nice to keep it there but use a little more of the blank vertical space. I can mock it up if my comments aren't clear. Appreciate your consideration!

**Comment by baf** [comment]
![image](https://github.com/user-attachments/assets/87999885-9b50-44b4-92bd-257927fa4d79)
![image](https://github.com/user-attachments/assets/033f7d2f-9ae3-4c7a-ba97-992031520633)

Here are two potential mockups of what I had in mind (credit to Top Gear for the amazing example vehicle).

**Comment by WJDDesigns** [comment]
I like all of this, thanks for your mockups which have huge potential! Now I will go back and see what I can do!

**Comment by baf** [comment]
Thanks much!

**Comment by WJDDesigns** [comment]
![image](https://github.com/user-attachments/assets/f98e5db2-491f-4172-a6be-9148b70c4523)

Next Update - Layout Coices

**Comment by baf** [comment]
Nice, looks great!
