### ISSUE TITLE
Added in V1.6.0-beta3 - soon to public release.

### ISSUE THREAD

**Issue by Amokk123** [WJDDesigns/Ultra-Vehicle-Card#95]
Added in V1.6.0-beta3 - soon to public release.

_Originally posted by @WJDDesigns in https://github.com/WJDDesigns/Ultra-Vehicle-Card/issues/85#issuecomment-2316554385_

**Comment by Amokk123** [comment]
Norwegian language is added in this release. But i can't get it to work. Cache is refresh. Even tried a new browser, first ti show this card. Tried uninstall. Reboot HA. Install, rebooted Ha, but no Norwegian. What am i missing herre?

**Comment by WJDDesigns** [comment]
I found out that in HA there is not NO but NB and NN for the two Norwegian languages that you can select from. Next beta or full update will have this working.
