### ISSUE TITLE
mdi icon colors

### ISSUE THREAD

**Issue by pathia** [WJDDesigns/Ultra-Vehicle-Card#99]
I've only just discovered this awesome card. Thanks!
I'm having trouble getting the mdi: icon colored. Is this something that should be working or is the option still under development.
In both Firefox and Chrome I get a color wheel but no way to actually select something. Also, pasting in a hex color code doesn't work.

**Comment by WJDDesigns** [comment]
What version are you on as this has been working fine for quite sometime and can be used on mobile as well.

**Comment by pathia** [comment]
Hi👋
1.5.9

**Comment by WJDDesigns** [comment]
Can you try in the newest update 1.6.0?

**Comment by pathia** [comment]
> Can you try in the newest update 1.6.0?

Unfortunately no it also doesn't work. Even when I just selected a color it doesn't show the hex code in the box. And saving also doesn't seem to do anything.

**Comment by pathia** [comment]
In this case I used the default Samsung internet browser on my galaxy s22 (so android)

**Comment by WJDDesigns** [comment]
> In this case I used the default Samsung internet browser on my galaxy s22 (so android) 

Can you try any other device or browser?

**Comment by pathia** [comment]
I think I found something: Whenever I only open the edit card dialog I get these errors in my log:
```
2024-09-16 09:43:22.981 ERROR (MainThread) [frontend.js.modern.202409060] Uncaught error from Firefox 130.0 on Windows 10
TypeError: can't define property "binary_sensor.skoda_octavia_combi_doors_locked": Object is not extensible
_handleStateConfigChange (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2970:7)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
_updateConfig (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:186:10)
_valueChanged (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:158:12)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
dispatchEvent (mwc-list-base.ts:409:13)
notifySelected (mwc-list-foundation.ts:410:17)
setSingleSelectionAtIndex_ (mwc-list-foundation.ts:194:11)
2024-09-16 09:43:22.982 ERROR (MainThread) [frontend.js.modern.202409060] Uncaught error from Firefox 130.0 on Windows 10
TypeError: can't define property "binary_sensor.skoda_octavia_combi_doors_locked": Object is not extensible
_handleStateConfigChange (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2970:7)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
_updateConfig (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:186:10)
_valueChanged (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:158:12)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
dispatchEvent (mwc-list-base.ts:409:13)
notifySelected (mwc-list-foundation.ts:410:17)
setSingleSelectionAtIndex_ (mwc-list-foundation.ts:194:11)
2024-09-16 09:43:22.985 ERROR (MainThread) [frontend.js.modern.202409060] Uncaught error from Firefox 130.0 on Windows 10
TypeError: can't define property "inactiveState": Object is not extensible
_handleStateConfigChange (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2973:71)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
_updateConfig (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:186:10)
_valueChanged (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:158:12)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
dispatchEvent (mwc-list-base.ts:409:13)
notifySelected (mwc-list-foundation.ts:410:17)
setSingleSelectionAtIndex_ (mwc-list-foundation.ts:194:11)
2024-09-16 09:43:22.985 ERROR (MainThread) [frontend.js.modern.202409060] Uncaught error from Firefox 130.0 on Windows 10
TypeError: can't define property "activeState": Object is not extensible
_handleStateConfigChange (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2973:71)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
_updateConfig (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:186:10)
_valueChanged (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:158:12)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
dispatchEvent (mwc-list-base.ts:409:13)
notifySelected (mwc-list-foundation.ts:410:17)
setSingleSelectionAtIndex_ (mwc-list-foundation.ts:194:11)
2024-09-16 09:43:22.985 ERROR (MainThread) [frontend.js.modern.202409060] Uncaught error from Firefox 130.0 on Windows 10
TypeError: can't define property "inactiveState": Object is not extensible
_handleStateConfigChange (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2973:71)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
_updateConfig (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:186:10)
_valueChanged (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:158:12)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
dispatchEvent (mwc-list-base.ts:409:13)
notifySelected (mwc-list-foundation.ts:410:17)
setSingleSelectionAtIndex_ (mwc-list-foundation.ts:194:11)
2024-09-16 09:43:22.985 ERROR (MainThread) [frontend.js.modern.202409060] Uncaught error from Firefox 130.0 on Windows 10
TypeError: can't define property "activeState": Object is not extensible
_handleStateConfigChange (/hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card-editor.js:2973:71)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
_updateConfig (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:186:10)
_valueChanged (/hacsfiles/Ultra-Vehicle-Card/state-dropdown.js:158:12)
handleEvent (/lit-html@1.4.1/lib/parts.js:462:18)
EventPart/this.__boundHandleEvent (/lit-html@1.4.1/lib/parts.js:428:41)
dispatchEvent (mwc-list-base.ts:409:13)
notifySelected (mwc-list-foundation.ts:410:17)
setSingleSelectionAtIndex_ (mwc-list-foundation.ts:194:11)

```

**Comment by WJDDesigns** [comment]
Please update to 1.6.1 - restart Home Assistant and clear cache on your browser.

**Comment by pathia** [comment]
Tried that, restarted HA and even used a private window but unfortunately no.
I'm beginning to think it has to do with my sensors (Skoda Connect)
For the record, I'm talking about these icons:
![afbeelding](https://github.com/user-attachments/assets/1b292683-6ef1-431c-af26-a821a50d46a3)

I selected binary sensors, is that okay ?

**Comment by pathia** [comment]
I've now changed the icon colors using the raw yaml code editor. So this fixes it somehow.
The only thing left are the errors in my log when editting the card.

**Comment by WJDDesigns** [comment]
Can you try making a new card from scratch? You should not have any errors. Also make sure you clear cache and try a different browser to see if there are caching issues.

**Comment by dynamicpete** [comment]
Hi,
I've the same issue.
Allready tried different browser (Chromium, Vivalid, Firefox) on Ubuntu linux. 
Clearing cache and creating a new card from scratch doesn't help unfortunatelly.
It looks like the problem is somehow related to the color picker...

**Comment by pathia** [comment]
I tried. But it didn't solve it .

**Comment by WJDDesigns** [comment]
Try version 1.6.3 - RESTART HOME ASSISTANT AND CLEAR CACHE - please :)

**Comment by sNiXx** [comment]
There is indeed some weird caching issue. I have been struggling with this for some time as well.

I am currently on version 1.6.7 and am still seeing this behavior. When I use a private window (Chromium-based browser) for Home Assistant, I can change one color exactly once and after that it stops working for all color pickers (manually typing, selecting or resetting does not work). I can repeat and reproduce by using a new private window.

**Comment by WJDDesigns** [comment]
> There is indeed some weird caching issue. I have been struggling with this for some time as well.
> 
> I am currently on version 1.6.7 and am still seeing this behavior. When I use a private window (Chromium-based browser) for Home Assistant, I can change one color exactly once and after that it stops working for all color pickers (manually typing, selecting or resetting does not work). I can repeat and reproduce by using a new private window.

What exact browser/OS are you using?

**Comment by sNiXx** [comment]
I tested using Brave and LibreWolf browsers on an Zorin OS (Ubuntu-based distro)

**Comment by sNiXx** [comment]
Oh, and changing to the YAML editor seems to be consuming massive amounts of resources - is that expected? It is really hard to edit anything like that.
